### ISSUE TITLE
how to modify host

### ISSUE THREAD

**Issue by logan2013** [wrysunny/redis_assistant_fun#1]

**Comment by wrysunny** [comment]
修改C:\Windows\System32\drivers\etc\hosts文件

**Comment by logan2013** [comment]
127.0.0.1 littletips.redisant.com
试了不行，求指导

**Comment by wrysunny** [comment]
當時分析的是RedisAssistant 1.1.8.2版本

對應的地址為 www.redisant.cn

127.0.0.1 www.redisant.cn
最新版沒有測試，不確定地址和驗證邏輯有沒有進行修改

logan2013 ***@***.***> 于2023年1月6日周五 09:54写道：
